CREATE TABLE IF NOT EXISTS f4_blackmarket (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    record_type VARCHAR(16) NOT NULL,
    citizenid VARCHAR(64) NOT NULL,
    reputation INT NULL,
    level INT NULL,
    purchase_uid VARCHAR(64) NULL,
    product_id VARCHAR(64) NULL,
    product_name VARCHAR(128) NULL,
    category_id VARCHAR(64) NULL,
    rarity VARCHAR(32) NULL,
    item_name VARCHAR(64) NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price INT NOT NULL DEFAULT 0,
    price_paid INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NULL,
    payment_account VARCHAR(16) NULL,
    failure_reason VARCHAR(64) NULL,
    metadata JSON NULL,
    purchased_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_history_purchase_uid (record_type, purchase_uid),
    KEY idx_record_type_citizenid (record_type, citizenid),
    KEY idx_record_type_purchased_at (record_type, purchased_at),
    KEY idx_record_type_created_at (record_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
